# Generated by Django 3.2.9 on 2021-11-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(related_name='related_cart', to='musicapp.CartProduct', verbose_name='Продукт для корзины'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_order',
            field=models.ManyToManyField(related_name='related_customer', to='musicapp.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('is_ready', 'Заказ готов'), ('in_progress', 'Заказ в обработке'), ('completed', 'Заказ получен покупателем')], default='new', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
