# Generated by Django 3.2.9 on 2021-11-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_auto_20211114_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='genry',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Заказ получен покупателем'), ('is_ready', 'Заказ готов'), ('new', 'Новый заказ'), ('in_progress', 'Заказ в обработке')], default='new', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
