# Generated by Django 3.2.9 on 2021-11-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_auto_20211114_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Исполнитель/группа', 'verbose_name_plural': 'Исполнители/группы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Заказ получен покупателем'), ('new', 'Новый заказ'), ('is_ready', 'Заказ готов'), ('in_progress', 'Заказ в обработке')], default='new', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
