# Generated by Django 3.2.9 on 2021-11-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_auto_20211116_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Заказ в обработке'), ('completed', 'Заказ получен покупателем'), ('is_ready', 'Заказ готов'), ('new', 'Новый заказ')], default='new', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
