# Generated by Django 3.2.9 on 2021-11-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_auto_20211116_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('is_ready', 'Заказ готов'), ('completed', 'Заказ получен покупателем'), ('in_progress', 'Заказ в обработке'), ('new', 'Новый заказ')], default='new', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
